"""
Embedding database operations — mixin for the Database class.
"""

from datetime import datetime, timezone
from typing import List, Dict, Optional, Union, Sequence


class DatabaseEmbeddingsMixin:

    def add_embedding(
        self,
        vector: List[float],
        model: str,
        cost: float = 0.0
    ) -> int:
        """
        Add an embedding vector to the database.

        Args:
            vector (List[float]): Embedding vector (typically 1024 dimensions)
            model (str): Model used (e.g., "voyage-3")
            cost (float): Cost to generate this embedding

        Returns:
            int: ID of the newly created embedding

        USAGE:
            embedding_id = db.add_embedding(vector, "voyage-3", 0.000012)
            db.update_message_embedding(message_id, embedding_id)
        """
        from .embeddings import embedding_to_json
        vector_json = embedding_to_json(vector)
        timestamp = datetime.now(timezone.utc).isoformat() + "Z"

        query = """
            INSERT INTO embeddings (vector, model, created_at, cost)
            VALUES (?, ?, ?, ?)
        """
        params = (vector_json, model, timestamp, cost)

        return self.execute_write(query, params)

    def update_message_embedding(self, message_id: int, embedding_id: int) -> bool:
        """
        Link an embedding to a message.

        Args:
            message_id (int): The message ID
            embedding_id (int): The embedding ID

        Returns:
            bool: True if successful
        """
        query = "UPDATE messages SET embedding_id = ? WHERE id = ?"
        self.execute_write(query, (embedding_id, message_id))
        return True

    def get_messages_with_embeddings(
        self,
        tier: Optional[Union[str, Sequence[str]]] = None,
        after: Optional[str] = None,
        limit: Optional[int] = None
    ) -> List[Dict]:
        """
        Get all messages that have embeddings.

        Args:
            tier (str or list/tuple of str, optional): Filter by tier. A single
                string compiles to an exact match (WHERE tier = ?); a list/tuple
                compiles to WHERE tier IN (...) so callers can search multiple
                tiers (e.g. ["active", "standard"]) in one query.
            after (str, optional): Only messages after this timestamp
            limit (int, optional): Maximum number of results

        Returns:
            List[dict]: Messages with their embeddings

        RETURN FORMAT:
            Each dict includes:
            - All message fields (id, content, timestamp, etc.)
            - embedding_vector (JSON string)
            - embedding_model
        """
        conditions = ["embedding_id IS NOT NULL"]
        params = []

        if tier:
            if isinstance(tier, (list, tuple, set)):
                tiers = list(tier)
                placeholders = ", ".join(["?"] * len(tiers))
                conditions.append(f"tier IN ({placeholders})")
                params.extend(tiers)
            else:
                conditions.append("tier = ?")
                params.append(tier)

        if after:
            conditions.append("timestamp >= ?")
            params.append(after)

        query = f"""
            SELECT m.*, e.vector as embedding_vector, e.model as embedding_model
            FROM messages m
            INNER JOIN embeddings e ON m.embedding_id = e.id
            WHERE {' AND '.join(conditions)}
            ORDER BY m.timestamp DESC
        """

        if limit:
            query += f" LIMIT {limit}"

        results = self.execute_query(query, tuple(params))
        return [dict(row) for row in results]

    def delete_embedding(self, embedding_id: int) -> bool:
        """Delete an embedding row (used when re-embedding replaces a stale vector)."""
        self.execute_write("DELETE FROM embeddings WHERE id = ?", (embedding_id,))
        return True

    def count_messages_needing_migration(
        self,
        current_model: str,
        max_chars: int = 15000
    ) -> int:
        """
        Count messages whose embedding is missing OR was generated by a different
        model than the current provider's model.

        Excludes messages that can never be embedded (empty or larger than
        `max_chars`, matching background.py's embedding guard) so a completed
        migration can genuinely reach 0 pending.
        """
        query = """
            SELECT COUNT(*)
            FROM messages m
            LEFT JOIN embeddings e ON m.embedding_id = e.id
            WHERE m.content IS NOT NULL
              AND TRIM(m.content) <> ''
              AND LENGTH(m.content) <= ?
              AND (m.embedding_id IS NULL OR e.model IS NULL OR e.model != ?)
        """
        results = self.execute_query(query, (max_chars, current_model))
        return results[0][0] if results else 0

    def get_messages_needing_migration(
        self,
        current_model: str,
        limit: int = 50,
        max_chars: int = 15000
    ) -> List[Dict]:
        """
        Fetch a batch of messages that need (re-)embedding for the current model.

        Progress state IS the `embeddings.model` provenance column — re-running
        this query naturally returns only the rows still outstanding, so the
        migration is idempotent and resumable with no separate progress table.
        """
        query = """
            SELECT m.id, m.content, m.embedding_id
            FROM messages m
            LEFT JOIN embeddings e ON m.embedding_id = e.id
            WHERE m.content IS NOT NULL
              AND TRIM(m.content) <> ''
              AND LENGTH(m.content) <= ?
              AND (m.embedding_id IS NULL OR e.model IS NULL OR e.model != ?)
            ORDER BY m.id ASC
            LIMIT ?
        """
        results = self.execute_query(query, (max_chars, current_model, limit))
        return [dict(row) for row in results]

    def get_messages_without_embeddings(self, limit: Optional[int] = None) -> List[Dict]:
        """
        Get messages that haven't been embedded yet.

        Args:
            limit (int, optional): Maximum number to return

        Returns:
            List[dict]: Messages without embeddings

        USE CASE:
        When running Phase 2 embedding on existing messages.
        """
        query = """
            SELECT *
            FROM messages
            WHERE embedding_id IS NULL
            ORDER BY timestamp ASC
        """

        if limit:
            query += f" LIMIT {limit}"

        results = self.execute_query(query)
        return [dict(row) for row in results]
